apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-secret-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: api-secret-demo

  template:
    metadata:
      labels:
        app: api-secret-demo

    spec:
      serviceAccountName: api-sa

      containers:
      - name: api

        image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/api-secret-demo:latest

        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: api-config