name: Deploy EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:

      # 1️⃣ Baixa o código
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configura AWS CLI
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Login no ECR
      - name: Login ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4️⃣ Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t api-secret-demo:latest .

      # 5️⃣ Tag da imagem para o ECR
      - name: Tag Docker image
        run: |
          docker tag api-secret-demo:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/api-secret-demo:latest

      # 6️⃣ Push da imagem para o ECR
      - name: Push Docker image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/api-secret-demo:latest

      # 7️⃣ Deploy no EKS
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/